name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel git zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build APK
      run: |
        buildozer -v android debug

    - uses: actions/upload-artifact@v4
      with:
        name: GaneshUtsavApp
        path: bin/*.apk
