name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel git zip unzip openjdk-17-jdk wget tar
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Install Android SDK & Build Tools
      run: |
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"
        echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Build APK
      run: |
        buildozer -v android debug

    - uses: actions/upload-artifact@v4
      with:
        name: GaneshUtsavApp
        path: bin/*.apk
